gui:
    theme:
        lightTheme: false
        activeBorderColor:
            - '#82AAFF'
            - bold
        inactiveBorderColor:
            - '#1D3B53'
        optionsTextColor:
            - '#7FDBCA'
        selectedLineBgColor:
            - '#1E2D3D'
        selectedRangeBgColor:
            - '#2C3040'
        cherryPickedCommitBgColor:
            - '#C792EA'
        cherryPickedCommitFgColor:
            - '#011627'
        markedBaseCommitBgColor:
            - '#EF5350'
        markedBaseCommitFgColor:
            - '#011627'
        unstagedChangesColor:
            - '#EF5350'
        defaultFgColor:
            - '#D6DEEB'
        searchingActiveBorderColor:
            - '#C792EA'
        authorColor:
            - '#7FDBCA'
        branchColor:
            - '#82AAFF'
    border: rounded
    showFileTree: true
    nerdFontsVersion: '3'
    showCommandLog: false
    showBottomLine: true
git:
    pagers:
        - colorArg: always
          pager: delta --dark --paging=never
customCommands:
    - key: 'R'
      context: 'global'
      command: 'git fetch --all --prune && git pull --rebase'
      description: 'Actualizar repositorio remoto'
